# vim :set ts=2 sw=2 sts=2 et :
---
language: python
cache: pip

sudo: false

matrix:
  include:
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=flake8
    - env: TOXENV=isort

services:
  - postgresql

env:
  - DATABASE_URL=postgres://postgres@localhost/postgres

install:
  - pip install tox

script:
  - tox
